version: "3"

services:

  functions:
    image: node:10-slim
    volumes:
      - .:/lambda
    working_dir: /lambda
    ports:
      - "9000:9000"
    env_file:
      - .env
    entrypoint: "node_modules/netlify-lambda/bin/cmd.js"
    command: ["serve", "./src/functions"]

  grunt:
    build: .
    depends_on:
      - functions
    volumes:
      - .:/chano4mayor
    working_dir: /chano4mayor

  nginx:
    image: nginx:latest
    depends_on:
      - grunt
    ports:
      - "1234:1234"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/dev.conf
      - .:/usr/share/nginx/html/chano4mayor
