#!/bin/bash

set -eo pipefail

function usage() {
    echo -n "Usage: $(basename "$0")

Clean up unused Docker resources to free disk space.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Stop containers and shut down the network
        docker-compose down

        # Remove any dangling volumes and images.
        docker images -qf dangling=true | xargs -r docker rmi
        docker volume ls -qf dangling=true | xargs -r docker volume rm
    fi
fi
